from datetime import datetime
from typing import Any, Protocol

from ..domain.entities import (
    Attachment,
    CampaignSender,
    EmailCampaign,
    EmailJob,
    EmailTemplate,
    ProviderProfile,
    RecipientSequenceState,
    RefreshToken,
    Sender,
    SenderCooldown,
    SequenceStep,
    TrackingEvent,
    User,
    WarmupSchedule,
)
from ..domain.enums import CampaignStatus, EmailStatus, TrackingEventType


class UserRepository(Protocol):
    async def get(self, user_id: str) -> User | None: ...
    async def upsert_google_user(
        self, google_id: str, email: str, name: str, avatar_url: str | None
    ) -> tuple[User, bool]: ...


class RefreshTokenRepository(Protocol):
    async def create(self, token: str, user_id: str, expires_at: datetime) -> RefreshToken: ...
    async def get_by_token(self, token: str) -> RefreshToken | None: ...
    async def revoke(self, token: str) -> None: ...
    async def delete_stale(self, revoked_before: datetime, now: datetime) -> int: ...


class SenderRepository(Protocol):
    async def create(self, sender: Sender) -> Sender: ...
    async def get(self, sender_id: str) -> Sender | None: ...
    async def get_owned(self, sender_id: str, user_id: str) -> Sender | None: ...
    async def list_for_user(self, user_id: str) -> list[Sender]: ...
    async def list_by_ids_for_user(self, sender_ids: list[str], user_id: str) -> list[Sender]: ...
    async def update(self, sender: Sender) -> Sender: ...


class ProviderProfileRepository(Protocol):
    async def get_by_host(self, smtp_host: str) -> ProviderProfile | None: ...
    async def get_wildcard(self) -> ProviderProfile | None: ...
    async def get(self, profile_id: str) -> ProviderProfile | None: ...


class WarmupScheduleRepository(Protocol):
    async def get_by_sender(self, sender_id: str) -> WarmupSchedule | None: ...
    async def create(self, schedule: WarmupSchedule) -> WarmupSchedule: ...


class SenderCooldownRepository(Protocol):
    async def get_by_sender(self, sender_id: str) -> SenderCooldown | None: ...
    async def upsert(
        self, sender_id: str, consecutive_errors: int, cooldown_until: datetime | None
    ) -> None: ...


class RateLimitRepository(Protocol):
    async def minute_count(self, sender_id: str, minute_window: datetime) -> int: ...
    async def hour_count(self, sender_id: str, hour_window: datetime) -> int: ...
    async def increment(
        self, sender_id: str, minute_window: datetime, hour_window: datetime
    ) -> None: ...
    async def delete_older_than(self, cutoff: datetime) -> int: ...


class CampaignRepository(Protocol):
    async def create(self, campaign: EmailCampaign) -> EmailCampaign: ...
    async def get(self, campaign_id: str) -> EmailCampaign | None: ...
    async def list_for_user(self, user_id: str, status: CampaignStatus | None = None) -> list[EmailCampaign]: ...
    async def search(
        self,
        user_id: str,
        query: str | None,
        status: CampaignStatus | None,
        sender_id: str | None,
        date_from: datetime | None,
        date_to: datetime | None,
    ) -> list[EmailCampaign]: ...
    async def update_status_if(
        self,
        campaign_id: str,
        expected: CampaignStatus,
        target: CampaignStatus,
        pause_reason: str | None = None,
    ) -> bool: ...
    async def list_by_status(self, status: CampaignStatus) -> list[EmailCampaign]: ...
    async def list_paused_exhausted(self) -> list[EmailCampaign]: ...
    async def has_sequence_steps(self, campaign_id: str) -> bool: ...
    async def list_sequence_campaigns(
        self, statuses: list[CampaignStatus]
    ) -> list[EmailCampaign]: ...


class CampaignSenderRepository(Protocol):
    async def create_many(self, campaign_senders: list[CampaignSender]) -> None: ...
    async def list_for_campaign(self, campaign_id: str) -> list[CampaignSender]: ...


class EmailJobRepository(Protocol):
    async def create_many(self, jobs: list[EmailJob]) -> None: ...
    async def get(self, job_id: str) -> EmailJob | None: ...
    async def get_owned(self, job_id: str, user_id: str) -> EmailJob | None: ...
    async def update(self, job: EmailJob) -> EmailJob: ...
    async def claim_pending(self, job_id: str) -> bool: ...
    async def set_status_if(
        self, job_id: str, expected: EmailStatus, target: EmailStatus
    ) -> bool: ...
    async def list_for_campaign(self, campaign_id: str) -> list[EmailJob]: ...
    async def status_counts(self, campaign_id: str) -> dict[str, int]: ...
    async def non_terminal_count(self, campaign_id: str) -> int: ...
    async def cancel_pending(self, campaign_id: str) -> int: ...
    async def list_pending_for_campaign(self, campaign_id: str) -> list[EmailJob]: ...
    async def sent_count_today(self, sender_id: str, now: datetime) -> int: ...
    async def recent_outcomes(self, sender_id: str, since: datetime) -> list[EmailJob]: ...
    async def list_by_status(self, status: EmailStatus) -> list[EmailJob]: ...
    async def list_stale_sending(self, updated_before: datetime) -> list[EmailJob]: ...
    async def list_for_user(
        self,
        user_id: str,
        status: EmailStatus | None,
        order_by: str,
        descending: bool,
        limit: int,
        offset: int,
    ) -> list[EmailJob]: ...
    async def list_for_sender(self, sender_id: str, user_id: str) -> list[EmailJob]: ...
    async def search(
        self,
        user_id: str,
        query: str | None,
        status: EmailStatus | None,
        sender_id: str | None,
        date_field: str,
        date_from: datetime | None,
        date_to: datetime | None,
        starred: bool | None,
    ) -> list[EmailJob]: ...
    async def first_with_column_data(
        self, campaign_id: str, to_email: str
    ) -> EmailJob | None: ...


class AttachmentRepository(Protocol):
    async def create_many(self, attachments: list[Attachment]) -> None: ...
    async def list_for_campaign(self, campaign_id: str) -> list[Attachment]: ...
    async def owner_id_by_url(self, url: str) -> str | None: ...


class TemplateRepository(Protocol):
    async def create(self, template: EmailTemplate) -> EmailTemplate: ...
    async def get(self, template_id: str) -> EmailTemplate | None: ...
    async def list_for_user(self, user_id: str) -> list[EmailTemplate]: ...
    async def update(self, template: EmailTemplate) -> EmailTemplate: ...
    async def delete(self, template_id: str) -> None: ...
    async def name_exists(self, user_id: str, name: str, exclude_id: str | None = None) -> bool: ...


class SequenceStepRepository(Protocol):
    async def create_many(self, steps: list[SequenceStep]) -> None: ...
    async def get(self, step_id: str) -> SequenceStep | None: ...
    async def list_for_campaign(self, campaign_id: str) -> list[SequenceStep]: ...


class RecipientStateRepository(Protocol):
    async def create_many(self, states: list[RecipientSequenceState]) -> None: ...
    async def get(self, state_id: str) -> RecipientSequenceState | None: ...
    async def get_by_recipient(
        self, campaign_id: str, recipient_email: str
    ) -> RecipientSequenceState | None: ...
    async def list_for_campaign(self, campaign_id: str) -> list[RecipientSequenceState]: ...
    async def list_active(self, campaign_id: str) -> list[RecipientSequenceState]: ...
    async def active_count(self, campaign_id: str) -> int: ...
    async def advance_step(self, state_id: str, expected_step: int, next_step: int) -> bool: ...
    async def update(self, state: RecipientSequenceState) -> RecipientSequenceState: ...
    async def set_paused_all(self, campaign_id: str, paused: bool) -> int: ...
    async def set_replied(self, campaign_id: str, recipient_email: str, replied: bool) -> None: ...


class TrackingEventRepository(Protocol):
    async def create(self, event: TrackingEvent) -> None: ...
    async def email_job_exists(self, email_job_id: str) -> bool: ...
    async def unique_event_count(
        self, campaign_id: str, event_type: TrackingEventType
    ) -> int: ...
    async def list_for_campaign_jobs(
        self, campaign_id: str
    ) -> dict[str, list[TrackingEvent]]: ...
    async def list_click_urls(self, campaign_id: str) -> list[str]: ...


class EmailQueue(Protocol):
    async def enqueue_send(self, email_job_id: str, delay_ms: int = 0) -> None: ...


class Mailer(Protocol):
    async def verify_credentials(
        self, host: str, port: int, email: str, password: str
    ) -> bool: ...
    async def send(
        self,
        host: str,
        port: int,
        username: str,
        password: str,
        from_name: str | None,
        from_email: str,
        to_email: str,
        subject: str,
        text_body: str,
        html_body: str,
        attachments: list[tuple[str, bytes, str]],
    ) -> None: ...


class CredentialCipher(Protocol):
    def encrypt(self, plain_text: str) -> str: ...
    def decrypt(self, cipher_text: str) -> str: ...


class TokenSigner(Protocol):
    def sign_access_token(self, payload: dict[str, Any]) -> str: ...
    def sign_refresh_token(self, payload: dict[str, Any]) -> str: ...
    def verify_access_token(self, token: str) -> dict[str, Any]: ...
    def verify_refresh_token(self, token: str) -> dict[str, Any]: ...


class GoogleVerifier(Protocol):
    async def verify(self, id_token: str) -> dict[str, Any] | None: ...


class FileStorage(Protocol):
    async def save(self, filename: str, content: bytes) -> str: ...
    async def read(self, url: str) -> bytes: ...
    async def delete(self, url: str) -> None: ...
